from .views import *
from .player_view import *
from .club_view import *
from .calendar_views import *
from .tournament_view import *
from .news_views import *
from .functions import *
from .recommendation_view import *
from .GoR_calculator import *
from .error_views import *
from .partner_view import *
