# Generated by Django 4.1.7 on 2023-04-05 00:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=16, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
