# Generated by Django 4.1.7 on 2023-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Club title')),
                ('EGDName', models.CharField(blank=True, max_length=6, null=True, verbose_name='EGDName')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('GoLevel', models.CharField(max_length=3, verbose_name='GoLevel')),
                ('EGF_placement', models.PositiveIntegerField(default=0, verbose_name='EGF placement')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating')),
                ('clubs', models.ManyToManyField(related_name='players', to='webapp.club')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tournament name')),
                ('board_size', models.PositiveIntegerField(default=19, verbose_name='Board size')),
                ('rounds', models.PositiveIntegerField(verbose_name='Total rounds')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField(verbose_name='Game id')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=10, null=True, verbose_name='Result')),
                ('black_score', models.PositiveIntegerField(verbose_name='Black score')),
                ('white_score', models.PositiveIntegerField(verbose_name='White score')),
                ('board_number', models.PositiveIntegerField(default=0, verbose_name='BoardNumber')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('round_num', models.PositiveIntegerField(verbose_name='Round')),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='webapp.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tournament')),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='webapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.country'),
        ),
    ]
