# Generated by Django 4.1.7 on 2023-04-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='playerintournament',
            name='GoLevel',
            field=models.CharField(max_length=3, verbose_name='GoLevel'),
        ),
        migrations.AlterField(
            model_name='playerintournament',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция/место'),
        ),
    ]
