# Generated by Django 4.1.7 on 2023-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='schedule',
        ),
        migrations.AddField(
            model_name='club',
            name='breakfast_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Обед c'),
        ),
        migrations.AddField(
            model_name='club',
            name='breakfast_to',
            field=models.TimeField(blank=True, null=True, verbose_name='до'),
        ),
        migrations.AddField(
            model_name='club',
            name='schedule_from',
            field=models.TimeField(blank=True, null=True, verbose_name='С'),
        ),
        migrations.AddField(
            model_name='club',
            name='schedule_to',
            field=models.TimeField(blank=True, null=True, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='playerintournament',
            name='GoLevel',
            field=models.CharField(max_length=3, verbose_name='GoLevel'),
        ),
        migrations.AlterField(
            model_name='playerintournament',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция/место'),
        ),
        migrations.AddField(
            model_name='club',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, null=True, related_name='day_of_week', to='webapp.dayofweek'),
        ),
        migrations.AddField(
            model_name='club',
            name='days_of_work',
            field=models.ManyToManyField(blank=True, null=True, related_name='days_of_work', to='webapp.dayofweek'),
        ),
    ]
