# Generated by Django 4.1.7 on 2023-03-01 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'], code='invalid_extension', message=['Загрузите файл в формате XML'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='EGF_placement',
        ),
        migrations.RemoveField(
            model_name='player',
            name='GoLevel',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
        migrations.AddField(
            model_name='player',
            name='tournaments',
            field=models.ManyToManyField(through='webapp.PlayerInTournament', to='webapp.tournament'),
        ),
        migrations.AddField(
            model_name='playerintournament',
            name='GoLevel',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='GoLevel'),
        ),
        migrations.AddField(
            model_name='playerintournament',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
    ]
