# Generated by Django 4.1.7 on 2023-04-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_city_city_alter_playerintournament_golevel_and_more'),
        ('webapp', '0002_dayofweek_remove_club_schedule_club_breakfast_from_and_more'),
    ]

    operations = [
    ]
