# Generated by Django 4.1.7 on 2023-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_merge_20230430_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_rank',
            field=models.CharField(blank=True, default='0k', max_length=3, null=True, verbose_name='GoLevel'),
        ),
        migrations.AlterField(
            model_name='playerintournament',
            name='GoLevel',
            field=models.CharField(default='10k', max_length=3, verbose_name='GoLevel'),
        ),
        migrations.AlterField(
            model_name='playerintournament',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция/место'),
        ),
    ]
