# Generated by Django 4.1.7 on 2023-05-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_player_current_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.city'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.region'),
        ),
    ]
