# Generated by Django 4.1.7 on 2023-03-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patronymic'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата турнира'),
        ),
    ]
