# Generated by Django 4.1.7 on 2023-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_tournament_city_alter_tournament_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, related_name='day_of_week', to='webapp.dayofweek'),
        ),
        migrations.AlterField(
            model_name='club',
            name='days_of_work',
            field=models.ManyToManyField(blank=True, related_name='days_of_work', to='webapp.dayofweek'),
        ),
    ]
