# Generated by Django 4.1.7 on 2023-05-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_tournament_city_alter_tournament_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.country'),
        ),
    ]
