# Generated by Django 4.1.7 on 2023-03-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_player_patronymic_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.city'),
        ),
    ]
