# Generated by Django 4.1.7 on 2023-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_player_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата турнира'),
        ),
    ]
