# Generated by Django 4.1.7 on 2023-05-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_club_day_of_week_alter_club_days_of_work'),
        ('webapp', '0006_tournament_country'),
    ]

    operations = [
    ]
