# Generated by Django 4.1.7 on 2023-03-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_tournament_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Название события')),
                ('event_city', models.CharField(max_length=50, verbose_name='Город проведения')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
            ],
        ),
    ]
