# Generated by Django 4.1.7 on 2023-03-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_class',
            field=models.CharField(choices=[('all', 'Все классы'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='all', max_length=20, verbose_name='Класс Турнира'),
        ),
    ]
