# Generated by Django 4.1.7 on 2023-03-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_go_level',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='webapp.playerintournament', verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_players',
            field=models.ManyToManyField(related_name='clubs_players', to='webapp.player', verbose_name='Члены клуба'),
        ),
    ]
