# Generated by Django 4.1.7 on 2023-03-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_calendar'),
        ('webapp', '0008_tournament_tournament_class'),
    ]

    operations = [
    ]
