# Generated by Django 4.1.7 on 2023-05-17 19:08

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(upload_to='carousel', validators=[webapp.models.validate_image_size], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='web_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
