# Generated by Django 4.1.7 on 2023-03-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_club_club_go_level_club_club_players'),
        ('webapp', '0011_alter_player_clubs'),
    ]

    operations = [
    ]
