# Generated by Django 4.1.7 on 2023-03-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_club_club_go_level_remove_club_club_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='webapp.city'),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logo', verbose_name='Лого'),
        ),
    ]
