# Generated by Django 4.1.7 on 2023-03-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_merge_20230306_0001'),
        ('webapp', '0014_club_city_club_logo'),
    ]

    operations = [
    ]
