# Generated by Django 4.1.7 on 2023-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_merge_20230307_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
