# Generated by Django 4.1.7 on 2023-03-13 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0017_remove_player_age_player_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coaches',
            field=models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
