# Generated by Django 4.1.7 on 2023-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_club_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
