# Generated by Django 4.1.7 on 2023-03-15 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0020_alter_calendar_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='coach', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
