# Generated by Django 4.1.7 on 2023-03-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0020_alter_calendar_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 01:20', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='text',
            field=models.TextField(default=1, max_length=5000, verbose_name='Описание события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='player',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='coach', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='regulations',
            field=models.TextField(blank=True, null=True, verbose_name='Regulations'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_class',
            field=models.CharField(blank=True, choices=[('all', 'Все классы'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='all', max_length=20, null=True, verbose_name='Class'),
        ),
    ]
