# Generated by Django 4.1.7 on 2023-03-17 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0021_calendar_author_calendar_created_at_calendar_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
