# Generated by Django 4.1.7 on 2023-03-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_player_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='regulations',
            field=models.TextField(blank=True, null=True, verbose_name='Regulations'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_class',
            field=models.CharField(blank=True, choices=[('all', 'Все классы'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='all', max_length=20, null=True, verbose_name='Class'),
        ),
    ]
