# Generated by Django 4.1.7 on 2023-03-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_participant_name_alter_participant_patronymic_and_more'),
        ('webapp', '0022_tournament_uploaded_by'),
    ]

    operations = [
    ]
