# Generated by Django 4.1.7 on 2023-03-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_player_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Black score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='White score'),
        ),
    ]
