# Generated by Django 4.1.7 on 2023-03-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_club_num_players'),
        ('webapp', '0024_remove_player_coach'),
    ]

    operations = [
    ]
