# Generated by Django 4.1.7 on 2023-03-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_game_black_score_alter_game_white_score'),
        ('webapp', '0025_merge_0024_club_num_players_0024_remove_player_coach'),
    ]

    operations = [
    ]
