# Generated by Django 4.1.7 on 2023-03-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_merge_20230321_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerintournament',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
    ]
