# Generated by Django 4.1.7 on 2023-03-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_playerintournament_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_rank',
            field=models.CharField(default='0k', max_length=3, verbose_name='GoLevel'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
