# Generated by Django 4.1.7 on 2023-03-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_player_current_rank_player_current_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.city'),
            preserve_default=False,
        ),
    ]
