# Generated by Django 4.1.7 on 2023-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_participant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
    ]
