# Generated by Django 4.1.7 on 2023-03-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_alter_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not confirmed', 'Not confirmed')], default='Not confirmed', max_length=50, verbose_name='Статус'),
        ),
    ]
