# Generated by Django 4.1.7 on 2023-03-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_alter_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.city'),
        ),
    ]
