# Generated by Django 4.1.7 on 2023-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_alter_participant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerintournament',
            name='rating_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating after'),
        ),
    ]
