# Generated by Django 4.1.7 on 2023-03-23 23:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_playerintournament_rating_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='club',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='club',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='club',
            name='web_link',
            field=models.URLField(blank=True, null=True, verbose_name='Интернет-ссылка'),
        ),
    ]
