# Generated by Django 4.1.7 on 2023-03-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_club_address_club_phonenumber_club_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания регистрации'),
        ),
    ]
