# Generated by Django 4.1.7 on 2023-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_calendar_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='EgdPin',
            field=models.PositiveIntegerField(default=0, max_length=8, verbose_name='EgdPin'),
            preserve_default=False,
        ),
    ]
