# Generated by Django 4.1.7 on 2023-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_player_egdpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='EgdPin',
            field=models.PositiveIntegerField(verbose_name='EgdPin'),
        ),
    ]
