# Generated by Django 4.1.7 on 2023-03-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_alter_player_egdpin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='patronymic',
        ),
    ]
