# Generated by Django 4.1.7 on 2023-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_alter_calendar_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='EgdPin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='EgdPin'),
        ),
    ]
