# Generated by Django 4.1.7 on 2023-03-30 04:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_alter_player_egdpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='webapp.calendar'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=16, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
