# Generated by Django 4.1.7 on 2023-03-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_alter_player_egdpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование партнера')),
                ('logo', models.ImageField(upload_to='partner_logo', verbose_name='Лого')),
                ('web_link', models.URLField(blank=True, null=True, verbose_name='Интернет-ссылка')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'partner',
            },
        ),
    ]
