# Generated by Django 4.1.7 on 2023-03-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_partner'),
        ('webapp', '0045_alter_calendar_deadline'),
    ]

    operations = [
    ]
