# Generated by Django 4.1.7 on 2023-03-30 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_alter_calendar_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания регистрации'),
            preserve_default=False,
        ),
    ]
