# Generated by Django 4.1.7 on 2023-03-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_playerintournament_golevel_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerintournament',
            name='GoLevel_after',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='GoLevel'),
        ),
    ]
