# Generated by Django 4.1.7 on 2023-04-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_alter_calendar_deadline'),
        ('webapp', '0048_alter_playerintournament_golevel_after'),
    ]

    operations = [
    ]
