# Generated by Django 4.1.7 on 2023-04-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_merge_20230331_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='patronymic',
        ),
    ]
