# Generated by Django 4.1.7 on 2023-04-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_merge_20230402_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='patronymic',
        ),
    ]
