# Generated by Django 4.1.7 on 2023-04-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_merge_20230401_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='patronymic',
        ),
    ]
