# Generated by Django 4.1.7 on 2023-04-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_alter_calendar_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerintournament',
            name='club',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.club'),
            preserve_default=False,
        ),
    ]
