# Generated by Django 4.1.7 on 2023-04-05 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_playerintournament_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerintournament',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.club'),
        ),
    ]
