# Generated by Django 4.1.7 on 2023-04-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_alter_playerintournament_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_gor_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Black GoR change'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_gor_change',
            field=models.FloatField(blank=True, null=True, verbose_name='White GoR change'),
        ),
    ]
