# Generated by Django 4.1.7 on 2023-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_game_black_gor_change_game_white_gor_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Статус модерации'),
        ),
    ]
