# Generated by Django 4.1.7 on 2023-04-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_tournament_is_moderated'),
        ('webapp', '0055_tournament_location_region_city_region_and_more'),
    ]

    operations = [
    ]
