# Generated by Django 4.1.7 on 2023-04-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_merge_20230409_1527'),
        ('webapp', '0056_merge_20230409_1613'),
    ]

    operations = [
    ]
