# Generated by Django 4.1.7 on 2023-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0057_alter_participant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
