# Generated by Django 4.1.7 on 2023-04-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0060_remove_tournament_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='calendar_image',
            field=models.ImageField(blank=True, null=True, upload_to='calendar_images', verbose_name='Изображение'),
        ),
    ]
