# Generated by Django 4.1.7 on 2023-04-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0061_calendar_calendar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notmoderatedtournament',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tournament name'),
        ),
    ]
