# Generated by Django 4.1.7 on 2023-04-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_alter_player_current_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='schedule',
        ),
        migrations.AddField(
            model_name='club',
            name='breakfast',
            field=models.TimeField(blank=True, null=True, verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='club',
            name='schedule_from',
            field=models.TimeField(blank=True, null=True, verbose_name='С'),
        ),
        migrations.AddField(
            model_name='club',
            name='schedule_to',
            field=models.TimeField(blank=True, null=True, verbose_name='До'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekend',
            field=models.CharField(blank=True, choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], default='Пн', max_length=50, null=True, verbose_name='Выходные'),
        ),
        migrations.AddField(
            model_name='club',
            name='work_from',
            field=models.CharField(blank=True, choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], default='Пн', max_length=50, null=True, verbose_name='Работаем с'),
        ),
        migrations.AddField(
            model_name='club',
            name='work_to',
            field=models.CharField(blank=True, choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб'), ('Вс', 'Вс')], default='Пн', max_length=50, null=True, verbose_name='До'),
        ),
    ]
