# Generated by Django 4.1.7 on 2023-04-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_alter_player_current_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция/место'),
        ),
    ]
