# Generated by Django 4.1.7 on 2023-04-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='playerintournament',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция/место'),
        ),
    ]
