# Generated by Django 4.1.7 on 2023-04-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_remove_club_schedule_club_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='breakfast',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='club',
            name='schedule_from',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='club',
            name='schedule_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='До'),
        ),
    ]
