# Generated by Django 4.1.7 on 2023-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0065_remove_player_position_playerintournament_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerintournament',
            name='game_id',
            field=models.PositiveIntegerField(verbose_name='ID in tournament(id_in_tournament)'),
        ),
    ]
