# Generated by Django 4.1.7 on 2023-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0065_alter_club_breakfast_alter_club_schedule_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='breakfast',
        ),
        migrations.AddField(
            model_name='club',
            name='breakfast_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Обед c'),
        ),
        migrations.AddField(
            model_name='club',
            name='breakfast_to',
            field=models.TimeField(blank=True, null=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='club',
            name='schedule_from',
            field=models.TimeField(blank=True, null=True, verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='club',
            name='schedule_to',
            field=models.TimeField(blank=True, null=True, verbose_name='До'),
        ),
    ]
