# Generated by Django 4.1.7 on 2023-04-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0067_dayofweek_remove_club_weekend_club_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='club',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, null=True, to='webapp.dayofweek'),
        ),
    ]
