# Generated by Django 4.1.7 on 2023-04-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_remove_club_day_of_week_club_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='work_from',
        ),
        migrations.RemoveField(
            model_name='club',
            name='work_to',
        ),
        migrations.AddField(
            model_name='club',
            name='days_of_work',
            field=models.ManyToManyField(blank=True, null=True, related_name='days_of_work', to='webapp.dayofweek'),
        ),
        migrations.AlterField(
            model_name='club',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, null=True, related_name='day_of_week', to='webapp.dayofweek'),
        ),
    ]
